sudo: required
os:
 - linux

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - cd ..
      - docker build -t yloc YLoc/
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-LowRes* Animals"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-LowRes Animals"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-LowRes Fungi"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-LowRes* Fungi"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-LowRes Plants"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-LowRes* Plants"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-HighRes Animals"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-HighRes Fungi"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-HighRes Plants"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-HighRes* Animals"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-HighRes* Fungi"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc-HighRes* Plants"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc+ Animals"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc+ Fungi"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc+ Plants"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc+* Animals"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc+* Fungi"
      - docker run --rm yloc python /YLoc/yloc.py /YLoc/test.fasta "YLoc+* Plants"
